name: MiApp
options:
  bundleIdPrefix: com.apple.mobile
  deploymentTarget:
    iOS: "17.0"
targets:
  MiApp:
    type: application
    platform: iOS
    sources:
      - path: MiApp
    dependencies:
      - sdk: AVFoundation.framework
    settings:
      base:
        INFOPLIST_FILE: MiApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.apple.mobile.MobileHouseArrest
        CODE_SIGNING_ALLOWED: NO
